package service;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.junit.jupiter.MockitoExtension;
import ru.yandex.practicum.filmorate.exceprion.ValidationException;
import ru.yandex.practicum.filmorate.model.User;
import ru.yandex.practicum.filmorate.service.UserService;

import java.time.LocalDate;

import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.assertj.core.api.AssertionsForClassTypes.assertThat;

@ExtendWith(MockitoExtension.class)
public class UserServiceTest {

    @InjectMocks
    private UserService service;

    @Test
    void validateUserEmailIsInvalidTest() {
        User user = new User();
        user.setEmail("invalid-email");
        user.setLogin("validLogin");
        user.setBirthday(LocalDate.of(1990, 1, 1));

        assertThatThrownBy(() -> service.createUser(user))
                .isInstanceOf(ValidationException.class);
    }

    @Test
    void validateUserEmailIsNullTest() {
        User user = new User();
        user.setLogin("validLogin");
        user.setBirthday(LocalDate.of(1990, 1, 1));

        assertThatThrownBy(() -> service.createUser(user))
                .isInstanceOf(ValidationException.class);
    }

    @Test
    void validateUserLoginIsNullTest() {
        User user = new User();
        user.setEmail("test@mail.ru");
        user.setBirthday(LocalDate.of(1990, 1, 1));

        assertThatThrownBy(() -> service.createUser(user))
                .isInstanceOf(ValidationException.class);
    }

    @Test
    void validateUserLoginContainsSpacesTest() {
        User user = new User();
        user.setEmail("test@mail.ru");
        user.setLogin("login with spaces");
        user.setBirthday(LocalDate.of(1990, 1, 1));

        assertThatThrownBy(() -> service.createUser(user))
                .isInstanceOf(ValidationException.class);
    }

    @Test
    void validateUserBirthdayIsInFutureTest() {
        User user = new User();
        user.setEmail("test@mail.ru");
        user.setLogin("validLogin");
        user.setBirthday(LocalDate.now().plusDays(1));

        assertThatThrownBy(() -> service.createUser(user))
                .isInstanceOf(ValidationException.class);
    }

    @Test
    void validateUserNameIsAutoGeneratedWhenNullTest() {
        User user = new User();
        user.setEmail("test@mail.ru");
        user.setLogin("validLogin");
        user.setBirthday(LocalDate.of(1990, 1, 1));

        User createdUser = service.createUser(user);

        assertThat(createdUser.getName()).isNotNull().isEqualTo("validLogin");
    }
}
