CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email VARCHAR(100) NOT NULL,
    login VARCHAR(100) NOT NULL UNIQUE, /* Можно и UNIQUE сделать в конце, но я не вижу смысла в этом, хотя так делают*/
    name VARCHAR(100),
    birthday DATE NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS age_ratings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(10) NOT NULL,
    CONSTRAINT pk_age_ratings PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS films (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    release_date DATE NOT NULL,
    duration INTEGER NOT NULL,
    age_rating_id BIGINT NOT NULL, /* Вывел в конец все зависимости, дабы не париться с порядком создания таблиц */
    CONSTRAINT pk_films PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS genres (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(50) NOT NULL UNIQUE,
    CONSTRAINT pk_genres PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS film_genres (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, /* В этой и ниже таблицах мы могли бы сделать
                                                            составной ключ, но мне лень)))) */
    film_id BIGINT NOT NULL,
    genre_id BIGINT NOT NULL,
    CONSTRAINT pk_film_genres PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS likes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    film_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    CONSTRAINT pk_likes PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS friendships (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id BIGINT NOT NULL,
    friend_id BIGINT NOT NULL,
    is_confirmed BOOLEAN,
    CONSTRAINT pk_friendships PRIMARY KEY (id)
);

ALTER TABLE films ADD CONSTRAINT fk_films_on_age_rating_id FOREIGN KEY (age_rating_id) REFERENCES age_ratings(id);

ALTER TABLE film_genres ADD CONSTRAINT fk_film_genres_on_film_id FOREIGN KEY (film_id) REFERENCES films(id);

ALTER TABLE film_genres ADD CONSTRAINT fk_film_genres_on_genre_id FOREIGN KEY (genre_id) REFERENCES genres(id);

ALTER TABLE likes ADD CONSTRAINT fk_likes_on_film_id FOREIGN KEY (film_id) REFERENCES films(id);

ALTER TABLE likes ADD CONSTRAINT fk_likes_on_user_id FOREIGN KEY (user_id) REFERENCES users(id);

ALTER TABLE friendships ADD CONSTRAINT fk_friendships_on_user_id FOREIGN KEY (user_id) REFERENCES users(id);

ALTER TABLE friendships ADD CONSTRAINT fk_friendships_on_friend_id FOREIGN KEY (friend_id) REFERENCES users(id);